### ISSUE TITLE
Problem in SINGULARITY IMAGE of Mitohpc

### ISSUE THREAD

**Issue by Yanranli007** [rkabiljo/MitoHPC2_LongReads_UCL#1]
Dear Renata,

I recall you previously encountered an issue with the "Singularity container: haplogrep3 fails" while using MitoHPC. Could you share how you resolved it?

I am facing a similar problem with HaploGrep 3.2.1. The error message I receive is as follows:

`HaploGrep 3 3.2.1
(c) 2022-2023 Sebastian Schönherr, Hansi Weissensteiner, Lukas Forer
Loading configuration from file 'haplogrep3.yaml' failed.
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target.`

I am operating in an environment without internet access. Could you please suggest any solutions or workarounds to resolve this issue? Thank you very much for your help!

Best regards, Yanran

**Comment by rkabiljo** [comment]
This issue is entirely unrelated to my repository which only describes how I have set up MitoHPC in my environment.  I am not even using the container.  I am going to close the issue.
